"""initial_schema

Revision ID: 2e20f1dac97e
Revises: 
Create Date: 2026-10-02 05:01:07.559535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e20f1dac97e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('nid_or_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_beneficiary_number'), 'beneficiaries', ['beneficiary_number'], unique=True)
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_name'), 'beneficiaries', ['name'], unique=False)
    op.create_index(op.f('ix_beneficiaries_phone'), 'beneficiaries', ['phone'], unique=False)
    op.create_index(op.f('ix_beneficiaries_status'), 'beneficiaries', ['status'], unique=False)
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_donor_number'), 'donors', ['donor_number'], unique=True)
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_index(op.f('ix_donors_name'), 'donors', ['name'], unique=False)
    op.create_index(op.f('ix_donors_phone'), 'donors', ['phone'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_code'), 'groups', ['code'], unique=True)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_index(op.f('ix_groups_status'), 'groups', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('nid_or_id', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('monthly_contribution_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_full_name'), 'members', ['full_name'], unique=False)
    op.create_index(op.f('ix_members_group_id'), 'members', ['group_id'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=60), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('flow_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversal_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_transaction_id'], ['financial_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_created_by_id'), 'financial_transactions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_flow_type'), 'financial_transactions', ['flow_type'], unique=False)
    op.create_index(op.f('ix_financial_transactions_group_id'), 'financial_transactions', ['group_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_is_reversed'), 'financial_transactions', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_financial_transactions_related_entity_id'), 'financial_transactions', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_related_entity_type'), 'financial_transactions', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_number'), 'financial_transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    op.create_table('member_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('nid_or_id', sa.String(length=100), nullable=True),
    sa.Column('proposed_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason_for_joining', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_group_id', sa.Integer(), nullable=True),
    sa.Column('created_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_applications_id'), 'member_applications', ['id'], unique=False)
    op.create_index(op.f('ix_member_applications_phone'), 'member_applications', ['phone'], unique=False)
    op.create_index(op.f('ix_member_applications_status'), 'member_applications', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('public_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_pages_id'), 'public_pages', ['id'], unique=False)
    op.create_index(op.f('ix_public_pages_slug'), 'public_pages', ['slug'], unique=True)
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_number', sa.String(length=60), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('contribution_month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'contribution_month', name='uq_member_month_contribution')
    )
    op.create_index(op.f('ix_contributions_contribution_month'), 'contributions', ['contribution_month'], unique=False)
    op.create_index(op.f('ix_contributions_contribution_number'), 'contributions', ['contribution_number'], unique=True)
    op.create_index(op.f('ix_contributions_group_id'), 'contributions', ['group_id'], unique=False)
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    op.create_index(op.f('ix_contributions_member_id'), 'contributions', ['member_id'], unique=False)
    op.create_index(op.f('ix_contributions_status'), 'contributions', ['status'], unique=False)
    op.create_index(op.f('ix_contributions_transaction_id'), 'contributions', ['transaction_id'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_number', sa.String(length=60), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_donation_amount'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donation_date'), 'donations', ['donation_date'], unique=False)
    op.create_index(op.f('ix_donations_donation_number'), 'donations', ['donation_number'], unique=True)
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_group_id'), 'donations', ['group_id'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_transaction_id'), 'donations', ['transaction_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_number', sa.String(length=60), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('payee', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_expense_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_transaction_id'), 'expenses', ['transaction_id'], unique=False)
    op.create_table('qard_hasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qard_number', sa.String(length=60), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_repayment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_repaid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('disbursed_date', sa.Date(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('repayment_schedule_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('disbursement_transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interest_rate = 0', name='check_zero_interest_rate'),
    sa.CheckConstraint('outstanding_amount >= 0', name='check_non_negative_outstanding'),
    sa.CheckConstraint('principal_amount > 0', name='check_positive_principal'),
    sa.CheckConstraint('total_repaid >= 0', name='check_non_negative_repaid'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disbursement_transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qard_hasan_beneficiary_id'), 'qard_hasan', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_qard_hasan_disbursed_date'), 'qard_hasan', ['disbursed_date'], unique=False)
    op.create_index(op.f('ix_qard_hasan_disbursement_transaction_id'), 'qard_hasan', ['disbursement_transaction_id'], unique=False)
    op.create_index(op.f('ix_qard_hasan_group_id'), 'qard_hasan', ['group_id'], unique=False)
    op.create_index(op.f('ix_qard_hasan_id'), 'qard_hasan', ['id'], unique=False)
    op.create_index(op.f('ix_qard_hasan_qard_number'), 'qard_hasan', ['qard_number'], unique=True)
    op.create_index(op.f('ix_qard_hasan_status'), 'qard_hasan', ['status'], unique=False)
    op.create_table('sadakah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sadakah_number', sa.String(length=60), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_sadakah_amount'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sadakah_beneficiary_id'), 'sadakah', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_sadakah_disbursement_date'), 'sadakah', ['disbursement_date'], unique=False)
    op.create_index(op.f('ix_sadakah_group_id'), 'sadakah', ['group_id'], unique=False)
    op.create_index(op.f('ix_sadakah_id'), 'sadakah', ['id'], unique=False)
    op.create_index(op.f('ix_sadakah_sadakah_number'), 'sadakah', ['sadakah_number'], unique=True)
    op.create_index(op.f('ix_sadakah_transaction_id'), 'sadakah', ['transaction_id'], unique=False)
    op.create_table('qard_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repayment_number', sa.String(length=60), nullable=False),
    sa.Column('qard_hasan_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('repayment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_positive_repayment_amount'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qard_hasan_id'], ['qard_hasan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qard_repayments_beneficiary_id'), 'qard_repayments', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_qard_repayments_group_id'), 'qard_repayments', ['group_id'], unique=False)
    op.create_index(op.f('ix_qard_repayments_id'), 'qard_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_qard_repayments_qard_hasan_id'), 'qard_repayments', ['qard_hasan_id'], unique=False)
    op.create_index(op.f('ix_qard_repayments_repayment_date'), 'qard_repayments', ['repayment_date'], unique=False)
    op.create_index(op.f('ix_qard_repayments_repayment_number'), 'qard_repayments', ['repayment_number'], unique=True)
    op.create_index(op.f('ix_qard_repayments_transaction_id'), 'qard_repayments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qard_repayments_transaction_id'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_repayment_number'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_repayment_date'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_qard_hasan_id'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_id'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_group_id'), table_name='qard_repayments')
    op.drop_index(op.f('ix_qard_repayments_beneficiary_id'), table_name='qard_repayments')
    op.drop_table('qard_repayments')
    op.drop_index(op.f('ix_sadakah_transaction_id'), table_name='sadakah')
    op.drop_index(op.f('ix_sadakah_sadakah_number'), table_name='sadakah')
    op.drop_index(op.f('ix_sadakah_id'), table_name='sadakah')
    op.drop_index(op.f('ix_sadakah_group_id'), table_name='sadakah')
    op.drop_index(op.f('ix_sadakah_disbursement_date'), table_name='sadakah')
    op.drop_index(op.f('ix_sadakah_beneficiary_id'), table_name='sadakah')
    op.drop_table('sadakah')
    op.drop_index(op.f('ix_qard_hasan_status'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_qard_number'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_id'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_group_id'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_disbursement_transaction_id'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_disbursed_date'), table_name='qard_hasan')
    op.drop_index(op.f('ix_qard_hasan_beneficiary_id'), table_name='qard_hasan')
    op.drop_table('qard_hasan')
    op.drop_index(op.f('ix_expenses_transaction_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_group_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_donations_transaction_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_group_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donation_number'), table_name='donations')
    op.drop_index(op.f('ix_donations_donation_date'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_contributions_transaction_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_status'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_member_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_group_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contribution_number'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contribution_month'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_public_pages_slug'), table_name='public_pages')
    op.drop_index(op.f('ix_public_pages_id'), table_name='public_pages')
    op.drop_table('public_pages')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_member_applications_status'), table_name='member_applications')
    op.drop_index(op.f('ix_member_applications_phone'), table_name='member_applications')
    op.drop_index(op.f('ix_member_applications_id'), table_name='member_applications')
    op.drop_table('member_applications')
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_number'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_related_entity_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_related_entity_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_is_reversed'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_group_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_flow_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_created_by_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_group_id'), table_name='members')
    op.drop_index(op.f('ix_members_full_name'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_groups_status'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_code'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_donors_phone'), table_name='donors')
    op.drop_index(op.f('ix_donors_name'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_donor_number'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_beneficiaries_status'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_phone'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_name'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_beneficiary_number'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
