"""create_monthly_contribution_settings_and_update_members

Revision ID: 936928033200
Revises: 2e20f1dac97e
Create Date: 2026-10-02 09:31:09.259997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936928033200'
down_revision: Union[str, Sequence[str], None] = '2e20f1dac97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_contribution_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_contribution_settings_effective_from'), 'monthly_contribution_settings', ['effective_from'], unique=True)
    op.create_index(op.f('ix_monthly_contribution_settings_id'), 'monthly_contribution_settings', ['id'], unique=False)
    op.drop_column('members', 'monthly_contribution_amount')
    
    # Seed initial default setting: BDT 100/month effective 2026-01-01
    op.execute(
        "INSERT INTO monthly_contribution_settings (amount, effective_from, notes, created_at, updated_at) "
        "VALUES (100.00, '2026-01-01', 'Initial Foundation Monthly Contribution Setting', NOW(), NOW()) "
        "ON CONFLICT (effective_from) DO NOTHING;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('monthly_contribution_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_monthly_contribution_settings_id'), table_name='monthly_contribution_settings')
    op.drop_index(op.f('ix_monthly_contribution_settings_effective_from'), table_name='monthly_contribution_settings')
    op.drop_table('monthly_contribution_settings')
    # ### end Alembic commands ###
